/**
 * FundRa — Database Seed Script
 *
 * Creates initial campaign data so the Explore page is not empty.
 * Run via: npx tsx src/lib/db/seed.ts
 * Or called automatically on first API read if db is empty.
 */

import type { DbCampaign } from "./engine";

export const SEED_CAMPAIGNS: DbCampaign[] = [
  {
    id: "camp_aura01",
    title: "Aura AI — Decentralized Compute Network",
    creator: "NeuroLabs",
    creatorAddress: "0x1a2B3c4D5e6F7a8B9c0D1e2F3a4B5c6D7e8F9a0B",
    description:
      "A decentralized GPU compute marketplace for AI model training at 60% lower cost than centralized providers.",
    longDescription:
      "Aura AI aggregates idle GPU capacity through a tokenized incentive layer, offering enterprise-grade ML compute. Uses proof-of-compute consensus paired with ERC-4626 yield vaults for sustainable funding.",
    category: "AI",
    network: "base",
    tvl: 2450000,
    aaveApy: 4.82,
    yieldGenerated: 48300,
    backerCount: 1243,
    status: "active",
    tags: ["GPU", "Machine Learning", "Compute"],
    targetRaise: 5000000,
    milestones: [
      {
        id: "ms_aura0_0",
        title: "Core Protocol Architecture",
        description: "Testnet contracts and compute verification consensus.",
        payoutPercentage: 20,
        status: "completed",
        votesFor: 892,
        votesAgainst: 34,
        quorumRequired: 500,
        completedAt: "2026-05-01T00:00:00Z",
      },
      {
        id: "ms_aura0_1",
        title: "GPU Node SDK & Dashboard",
        description: "Node operator SDK, monitoring dashboard, staking integration.",
        payoutPercentage: 30,
        status: "active",
        votesFor: 310,
        votesAgainst: 12,
        quorumRequired: 500,
        deliverableUrl: "https://github.com/neurolabs/aura-sdk",
      },
      {
        id: "ms_aura0_2",
        title: "Mainnet Launch",
        description: "Deploy to mainnet and onboard compute providers.",
        payoutPercentage: 50,
        status: "upcoming",
        votesFor: 0,
        votesAgainst: 0,
        quorumRequired: 500,
      },
    ],
    bondingCurve: {
      tokenName: "Aura Compute Token",
      tokenTicker: "AURA",
      currentPrice: 0.34,
      initialPrice: 0.01,
      reserveRatio: 0.33,
      totalSupply: 18500000,
      marketCap: 6290000,
    },
    createdAt: "2026-03-15T00:00:00Z",
  },
  {
    id: "camp_zksh01",
    title: "zkShield — Zero-Knowledge Privacy Layer",
    creator: "CipherCore",
    creatorAddress: "0x5e6F7a8B9c0D1e2F3a4B5c6D7e8F9a0B1c2D3e4F",
    description:
      "Modular ZK privacy middleware for confidential transactions and shielded DeFi positions across EVM chains.",
    longDescription:
      "zkShield provides a composable zero-knowledge proof layer built on Halo2. Privacy Pools backed by ERC-4626 vaults enable depositors to earn yield while contributing to network anonymity sets.",
    category: "Infrastructure",
    network: "ethereum",
    tvl: 1875000,
    aaveApy: 5.14,
    yieldGenerated: 32100,
    backerCount: 876,
    status: "active",
    tags: ["ZK Proofs", "Privacy", "Halo2"],
    targetRaise: 3000000,
    milestones: [
      {
        id: "ms_zksh0_0",
        title: "ZK Circuit Design & Audit",
        description: "Complete Halo2 circuit design and third-party security audit.",
        payoutPercentage: 25,
        status: "completed",
        votesFor: 654,
        votesAgainst: 18,
        quorumRequired: 400,
        completedAt: "2026-06-10T00:00:00Z",
      },
      {
        id: "ms_zksh0_1",
        title: "Testnet Privacy Pools",
        description: "Deploy shielded transaction pools on Sepolia with browser proof generation.",
        payoutPercentage: 35,
        status: "active",
        votesFor: 201,
        votesAgainst: 8,
        quorumRequired: 400,
      },
      {
        id: "ms_zksh0_2",
        title: "Mainnet & SDK Release",
        description: "Launch on Ethereum mainnet with developer SDK.",
        payoutPercentage: 40,
        status: "upcoming",
        votesFor: 0,
        votesAgainst: 0,
        quorumRequired: 400,
      },
    ],
    bondingCurve: {
      tokenName: "zkShield Token",
      tokenTicker: "ZKS",
      currentPrice: 0.52,
      initialPrice: 0.02,
      reserveRatio: 0.25,
      totalSupply: 9200000,
      marketCap: 4784000,
    },
    createdAt: "2026-04-02T00:00:00Z",
  },
  {
    id: "camp_liqf01",
    title: "LiquidFlow — Cross-Chain DeFi Engine",
    creator: "FlowFi",
    creatorAddress: "0x3a4B5c6D7e8F9a0B1c2D3e4F5a6B7c8D9e0F1a2B",
    description:
      "Intent-based cross-chain DeFi aggregator with MEV-protected swaps and unified yield farming.",
    longDescription:
      "LiquidFlow abstracts multi-chain DeFi complexity through an intent-based execution layer. Solvers compete to fill orders with optimal execution. Revenue flows back to ERC-4626 vault depositors.",
    category: "DeFi",
    network: "ethereum",
    tvl: 3120000,
    aaveApy: 5.67,
    yieldGenerated: 72400,
    backerCount: 1876,
    status: "active",
    tags: ["DEX", "Cross-Chain", "MEV Protection"],
    targetRaise: 8000000,
    milestones: [
      {
        id: "ms_liqf0_0",
        title: "Intent Engine Core",
        description: "Order book, solver network, intent matching engine.",
        payoutPercentage: 20,
        status: "completed",
        votesFor: 1245,
        votesAgainst: 45,
        quorumRequired: 800,
        completedAt: "2026-04-20T00:00:00Z",
      },
      {
        id: "ms_liqf0_1",
        title: "Cross-Chain Bridge Integration",
        description: "LayerZero and Hyperlane for cross-chain intent settlement.",
        payoutPercentage: 30,
        status: "completed",
        votesFor: 1089,
        votesAgainst: 67,
        quorumRequired: 800,
        completedAt: "2026-06-28T00:00:00Z",
      },
      {
        id: "ms_liqf0_2",
        title: "Public Mainnet & Yield Optimizer",
        description: "Launch mainnet aggregator with yield farming strategy router.",
        payoutPercentage: 50,
        status: "active",
        votesFor: 534,
        votesAgainst: 21,
        quorumRequired: 800,
      },
    ],
    bondingCurve: {
      tokenName: "LiquidFlow Token",
      tokenTicker: "FLOW",
      currentPrice: 1.24,
      initialPrice: 0.05,
      reserveRatio: 0.3,
      totalSupply: 12000000,
      marketCap: 14880000,
    },
    createdAt: "2026-02-08T00:00:00Z",
  },
];
